export const frameToPath: Record<string, string> = {
    "BALOR": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-Horus-BALOR.png",
    "BARBAROSSA": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-HA-BARBAROSSA.png",
    "BLACK WITCH": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-SSC-BLACK-WITCH.png",
    "BLACKBEARD": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-IPS-N-BLACKBEARD.png",
    "DEATH’S HEAD": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-SSC-DEATHS HEAD.png",
    "DRAKE": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-IPS-N-DRAKE.png",
    "DUSK WING": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-SSC-DUSK WING.png",
    "ENKIDU": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-HA-Enkidu.png",
    "EVEREST": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-GMS.png",
    "GENGHIS": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-HA-GENGHIS.png",
    "GOBLIN": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-Horus-GOBLIN.png",
    "GORGON": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-Horus-GORGON.png",
    "HYDRA": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-Horus-HYDRA.png",
    "ISKANDER": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-HA-ISKANDER.png",
    "KIDD": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-IPS-N-KIDD.png",
    "LANCASTER": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-IPS-N-LANCASTER.png",
    "MANTICORE": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-Horus-MANTICORE.png",
    "METALMARK": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-SSC-METALMARK.png",
    "MINOTAUR": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-Horus-MINOTAUR.png",
    "MONARCH": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-SSC-MONARCH.png",
    "MOURNING CLOAK": "systems/lancer/assets/retrograde-minis/Retrograde-SSC-MOURNING CLOAK.png",
    "NAPOLEON": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-HA-NAPOLEON.png",
    "NELSON": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-IPS-N-NELSON.png",
    "PEGASUS": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-Horus-PEGASUS.png",
    "RALEIGH": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-IPS-N-RALEIGH.png",
    "SAGARMATHA": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-GMS.png",
    "SALADIN": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-HA-SALADIN.png",
    "SHERMAN": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-HA-SHERMAN.png",
    "SWALLOWTAIL": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-SSC-SWALLOWTAIL.png",
    "TOKUGAWA": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-HA-TOKUGAWA.png",
    "TORTUGA": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-IPS-N-TORTUGA.png",
    "VLAD": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-IPS-N-VLAD.png",
    "ZHENG": "systems/lancer/assets/retrograde-minis/Retrograde-Minis-IPS-N-ZHENG.png"
}